name: env-aeropolis  
channels:
  - conda-forge
  - defaults
dependencies:
  - openblas
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.14
  - jpeg=9e
  - libbrotlicommon=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.22
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libiconv=1.16
  - libsodium=1.0.18
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - ncurses=6.4.20240210
  - pandoc=3.6.1
  - tzdata=2024b
  - xz=5.4.6
  - yaml=0.2.5
  - expat=2.6.4
  - icu=73.1
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libedit=3.1.20230828
  - libgfortran5=11.3.0
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libsqlite=3.45.3
  - libxgboost=2.1.1
  - lz4-c=1.9.4
  - openssl=3.4.0
  - pcre2=10.42
  - readline=8.2
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - brotli-bin=1.0.9
  - freetype=2.12.1
  - krb5=1.20.1
  - libclang13=14.0.6
  - libgfortran=5.0.0
  - libnghttp2=1.57.0
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libxml2=2.13.5
  - sqlite=3.45.3
  - tk=8.6.14
  - brotli=1.0.9
  - cyrus-sasl=2.1.28
  - gettext=0.21.0
  - lcms2=2.16
  - libclang=14.0.6
  - libcurl=8.11.1
  - libopenblas=0.3.21
  - openjpeg=2.5.2
  - python=3.12.4
  - appnope=0.1.3
  - attrs=24.3.0
  - backports=1.0
  - brotli-python=1.0.9
  - cached_property=1.5.2
  - certifi=2024.12.14
  - charset-normalizer=3.3.2
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=0.8.3
  - flit-core=3.10.1
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - json5=0.9.25
  - jsonpointer=2.0
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.4
  - libglib=2.78.4
  - markupsafe=2.1.3
  - mdurl=0.1.0
  - mistune=2.0.4
  - mysql=8.4.0
  - nest-asyncio=1.6.0
  - numpy-base=2.1.3
  - openldap=2.6.4
  - packaging=24.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - prometheus_client=0.21.0
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyobjc-core=10.1
  - pyparsing=3.2.0
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - setuptools=72.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - threadpoolctl=3.5.0
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - zipp=3.21.0
  - anyio=4.6.2.post1
  - asttokens=2.0.5
  - async-lru=2.0.4
  - babel=2.11.0
  - backports.functools_lru_cache=2.0.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - cached-property=1.5.2
  - cffi=1.17.1
  - comm=0.2.1
  - fonttools=4.51.0
  - glib-tools=2.78.4
  - h11=0.14.0
  - h2=4.1.0
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jupyterlab_pygments=0.1.2
  - libpq=17.2
  - markdown-it-py=2.2.0
  - matplotlib-inline=0.1.6
  - matplotlib-base=3.9.2
  - pandas=2.2.3
  - prompt-toolkit=3.0.43
  - scikit-learn=1.5.2
  - urllib3=2.2.3
  - gst-plugins-base=1.14.1
  - ipython=8.30.0
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter_client=8.6.0
  - pyqt=5.15.10
  - qtpy=2.4.1
  - referencing=0.30.2
  - rfc3339-validator=0.1.4
  - sip=6.7.12
  - terminado=0.17.1
  - tinycss2=1.2.1
  - typing-extensions=4.11.0
  - arrow=1.3.0
  - bottleneck=1.4.2
  - contourpy=1.3.1
  - fqdn=1.5.1
  - glib=2.78.4
  - httpcore=1.0.2
  - importlib_metadata=8.5.0
  - jsonschema-specifications=2023.7.1
  - jupyter_server_terminals=0.4.4
  - numexpr=2.10.1
  - patsy=1.0.1
  - platformdirs=3.10.0
  - rich=13.9.4
  - scipy=1.14.1
  - send2trash=1.8.2
  - stack_data=0.2.0
  - wcwidth=0.2.5
  - zstandard=0.23.0
  - argon2-cffi=21.3.0
  - gstreamer=1.14.1
  - httpx=0.27.0
  - isoduration=20.11.0
  - jsonschema=4.23.0
  - jupyter_core=5.7.2
  - matplotlib-base=3.9.2
  - pandas=2.2.3
  - prompt-toolkit=3.0.43
  - scikit-learn=1.5.2
  - urllib3=2.2.3
  - qt-main=5.15.2
  - seaborn=0.13.2
  - xgboost=2.1.1
  - jupyter_console=6.6.3
  - missingno=0.5.2
  - nbconvert-core=7.16.4
  - pyqt5-sip=12.13.0
  - qtconsole=5.6.0
  - jupyter_server=2.14.1
  - nbconvert-pandoc=7.16.4
  - jupyter-lsp=2.2.0
  - jupyterlab_server=2.27.3
  - nbconvert=7.16.4
  - notebook-shim=0.2.3
  - jupyterlab=4.2.5
  - notebook=7.2.2
  - jupyter=1.0.0
  - ipykernel=6.29.5 
  - pyampute=0.0.3